name: 'Go coverage report'
description: 'This action updates adds an HTML coverage report and SVG badge to your wiki'
branding:
  color: blue
  icon: award

inputs:
  report:
    description: Generate an HTML coverage report.
    default: true
  chart:
    description: Generate a coverage over time chart.
    default: false
  amend:
    description: Amend wiki, avoiding spurious commits.
    default: false

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Checkout wiki
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}.wiki
        path: ./.github/wiki/

    - name: Generate coverage report
      shell: bash
      env:
        INPUT_CHART:  ${{inputs.chart}}
        INPUT_REPORT: ${{inputs.report}}
      run: |
        ${{github.action_path}}/coverage.sh ./.github/wiki/

    - name: Push to wiki
      shell: bash
      run: |
        cd ./.github/wiki/
        git add --all
        git diff-index --quiet HEAD && exit
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        test ${{inputs.amend}} == "true" && \
          git commit --amend --no-edit && git push --force-with-lease || \
          git commit -m "Update coverage" && git push
